- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 200"
- label: "Author"
  message: "$payload.pull_request.user.login"
  color: "blue"
- label: "Size"
  message: "$additions"
  color: "orange"
- imageUrl: "https://gitlab.cern.ch/rest-for-physics/geant4lib/badges/$branchName/pipeline.svg"
  url: "https://gitlab.cern.ch/rest-for-physics/geant4lib/-/commits/$branchName"
